// Todos los estados de las órdenes internas, de los cuatro tipos. Qué estado sigue a cuál depende
// del tipo, y está en una sola tabla: internal-order-flow.ts.
//
// SO  NEW → ACCEPTED_BY_WAREHOUSE → PACKING → READY_FOR_RUNNER → IN_TRANSIT → DELIVERED_TO_STORE →
//     RECEIVED_BY_SELLER → (PENDING_PAYMENT → PAID | RETURN_REQUESTED → RETURNED |
//     ITEM_CHANGE_REQUESTED → RECEIVED_BY_SELLER). Una sub-orden termina en MERGED_INTO_PARENT.
// RE  RETURN_CREATED → WAITING_FOR_RUNNER → IN_TRANSIT_TO_WAREHOUSE → DELIVERED_TO_WAREHOUSE →
//     RECEIVED_BY_WAREHOUSE → RETURNED
// TR  TRANSFER_REQUESTED → WAITING_FOR_RUNNER → IN_TRANSIT → DELIVERED_TO_DESTINATION →
//     RECEIVED_BY_DESTINATION → TRANSFERRED
// RS  RESTOCK_REQUESTED → WAITING_FOR_RUNNER → IN_TRANSIT → DELIVERED_TO_STORE → RECEIVED_BY_STORE →
//     RESTOCKED
// CANCELLED: cualquiera, antes de que el corredor recoja.
export enum InternalOrderStatus {
  NEW = 'NEW',
  ACCEPTED_BY_WAREHOUSE = 'ACCEPTED_BY_WAREHOUSE',
  PACKING = 'PACKING',
  READY_FOR_RUNNER = 'READY_FOR_RUNNER',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED_TO_STORE = 'DELIVERED_TO_STORE',
  RECEIVED_BY_SELLER = 'RECEIVED_BY_SELLER',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  ITEM_CHANGE_REQUESTED = 'ITEM_CHANGE_REQUESTED',
  MERGED_INTO_PARENT = 'MERGED_INTO_PARENT',
  RETURN_CREATED = 'RETURN_CREATED',
  WAITING_FOR_RUNNER = 'WAITING_FOR_RUNNER',
  IN_TRANSIT_TO_WAREHOUSE = 'IN_TRANSIT_TO_WAREHOUSE',
  DELIVERED_TO_WAREHOUSE = 'DELIVERED_TO_WAREHOUSE',
  RECEIVED_BY_WAREHOUSE = 'RECEIVED_BY_WAREHOUSE',
  RETURNED = 'RETURNED',
  TRANSFER_REQUESTED = 'TRANSFER_REQUESTED',
  DELIVERED_TO_DESTINATION = 'DELIVERED_TO_DESTINATION',
  RECEIVED_BY_DESTINATION = 'RECEIVED_BY_DESTINATION',
  TRANSFERRED = 'TRANSFERRED',
  RESTOCK_REQUESTED = 'RESTOCK_REQUESTED',
  RECEIVED_BY_STORE = 'RECEIVED_BY_STORE',
  RESTOCKED = 'RESTOCKED',
  CANCELLED = 'CANCELLED',
}
