export enum NotificationEntityType {
  DISCOUNT_REQUEST = 'DISCOUNT_REQUEST',
  SALE_RETURN = 'SALE_RETURN',
  CASH_SESSION = 'CASH_SESSION',
  PRODUCT_DELETION_REQUEST = 'PRODUCT_DELETION_REQUEST',
}
