export enum NotificationEntityType {
  DISCOUNT_REQUEST = 'DISCOUNT_REQUEST',
  SALE_RETURN = 'SALE_RETURN',
  CASH_SESSION = 'CASH_SESSION',
  INVENTORY_BALANCE = 'INVENTORY_BALANCE',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  INTERNAL_ORDER = 'INTERNAL_ORDER',
}
